service: aws-serverless-project

custom:
  bucket: EXAMPLE
  dynamoDBTableName: dynamo_table
  prefix: FOO
plugins:
  - serverless-pseudo-parameters
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/${self:custom.prefix}/${self:custom.dynamoDBTableName}/*"
    - Effect: Allow
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/dynamo_table

functions:
  backup:
    handler: src/functions/post-dynamo/hanler.backup
    environment:
      STAGE: "${opt:stage, self:provider.stage}"
      BUCKET: "${self:custom.bucket}"
      TABLE: "${self:custom.dynamoDBTableName}"
      PREFIX: "${self:custom.prefix}"
    timeout: 300
  rds-storage-user:
    handler: src/functions/post-rds/handler.storage
    name: rds-storage-user
    events:
      - http:
        path: /postdata/user
        method: post
        cors: true
